# Generated by Django 2.1.1 on 2018-10-08 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20181004_2258'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medical_history',
            old_name='diabetes_mellitus',
            new_name='condition_active',
        ),
        migrations.RemoveField(
            model_name='medical_history',
            name='epilepsy',
        ),
        migrations.RemoveField(
            model_name='medical_history',
            name='others',
        ),
        migrations.RemoveField(
            model_name='medical_history',
            name='systematic_hypertension',
        ),
        migrations.AddField(
            model_name='medical_history',
            name='condition',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
