# Generated by Django 2.1.1 on 2018-10-17 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_authuserdemographic_first_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medical_history',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.AuthUserDemographic'),
        ),
    ]
