# Generated by Django 2.1.1 on 2018-11-15 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20181017_0505'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blood_pressure',
            old_name='bp',
            new_name='diastolic',
        ),
        migrations.AddField(
            model_name='blood_pressure',
            name='systolic',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
