# Generated by Django 2.1.1 on 2018-12-17 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20181115_1737'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yourname', models.CharField(max_length=255, null=True)),
                ('youremail', models.CharField(max_length=255, null=True)),
                ('yournumber', models.CharField(max_length=255, null=True)),
                ('subject', models.CharField(max_length=255, null=True)),
                ('message', models.CharField(max_length=1500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fasting_blood_sugar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('test_result', models.CharField(max_length=255, null=True)),
                ('saved_result', models.CharField(max_length=255, null=True)),
                ('test_date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.AuthUserDemographic')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Full_blood_count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('red_blood_cell', models.CharField(max_length=255, null=True)),
                ('hemoglobin', models.CharField(max_length=255, null=True)),
                ('hematocrit', models.CharField(max_length=255, null=True)),
                ('white_blood_cell', models.CharField(max_length=255, null=True)),
                ('platelet', models.CharField(max_length=255, null=True)),
                ('date', models.DateField()),
                ('next_test_date', models.DateField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.AuthUserDemographic')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Urine_test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('leukocytes', models.CharField(max_length=255, null=True)),
                ('nitrites', models.CharField(max_length=255, null=True)),
                ('urobilinogen', models.CharField(max_length=255, null=True)),
                ('protein', models.CharField(max_length=255, null=True)),
                ('ph_level', models.CharField(max_length=255, null=True)),
                ('blood_urine', models.CharField(max_length=255, null=True)),
                ('specific_gravity_test', models.CharField(max_length=255, null=True)),
                ('ketone', models.CharField(max_length=255, null=True)),
                ('bilirubin', models.CharField(max_length=255, null=True)),
                ('glucose', models.CharField(max_length=255, null=True)),
                ('date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.AuthUserDemographic')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='surgery',
            name='doctor',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='surgery',
            name='hospital',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
