# Generated by Django 2.1.1 on 2019-01-20 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20181217_0043'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lipid_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_cholesterol', models.CharField(max_length=255, null=True)),
                ('hdl_cholesterol', models.CharField(max_length=255, null=True)),
                ('ldl_cholesterol', models.CharField(max_length=255, null=True)),
                ('triglycerides', models.CharField(max_length=255, null=True)),
                ('lipid_profile_date', models.DateField()),
                ('next_lipid_test', models.DateField()),
                ('lipid_scan', models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='pic_folder/')),
                ('docs_comments', models.CharField(max_length=3000, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.AuthUserDemographic')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Liver_function_test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alt', models.CharField(max_length=255, null=True)),
                ('ast', models.CharField(max_length=255, null=True)),
                ('alp', models.CharField(max_length=255, null=True)),
                ('total_protein', models.CharField(max_length=255, null=True)),
                ('bilirubin', models.CharField(max_length=255, null=True)),
                ('bilirubin_direct', models.CharField(max_length=255, null=True)),
                ('ggt', models.CharField(max_length=255, null=True)),
                ('liver_test_date', models.DateField()),
                ('next_liver_test', models.DateField()),
                ('liver_scan', models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='pic_folder/')),
                ('docs_comments', models.CharField(max_length=3000, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.AuthUserDemographic')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Prostate_specific_antigen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('psa_total', models.CharField(max_length=255, null=True)),
                ('docs_comments', models.CharField(max_length=3000, null=True)),
                ('psa_test_date', models.DateField()),
                ('next_psa_test', models.DateField()),
                ('psa_scan', models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='pic_folder/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.AuthUserDemographic')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Renal_function_test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creatinine', models.CharField(max_length=255, null=True)),
                ('urea', models.CharField(max_length=255, null=True)),
                ('gfr', models.CharField(max_length=255, null=True)),
                ('renal_test_date', models.DateField()),
                ('next_renal_test', models.DateField()),
                ('renal_scan', models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='pic_folder/')),
                ('docs_comments', models.CharField(max_length=3000, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.AuthUserDemographic')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='full_blood_count',
            old_name='date',
            new_name='full_blood_count_date',
        ),
        migrations.RenameField(
            model_name='full_blood_count',
            old_name='next_test_date',
            new_name='next_full_blood_count_date',
        ),
        migrations.RenameField(
            model_name='urine_test',
            old_name='date',
            new_name='urine_test_date',
        ),
        migrations.RemoveField(
            model_name='urine_test',
            name='bilirubin',
        ),
        migrations.RemoveField(
            model_name='urine_test',
            name='blood_urine',
        ),
        migrations.RemoveField(
            model_name='urine_test',
            name='glucose',
        ),
        migrations.RemoveField(
            model_name='urine_test',
            name='ketone',
        ),
        migrations.RemoveField(
            model_name='urine_test',
            name='leukocytes',
        ),
        migrations.RemoveField(
            model_name='urine_test',
            name='nitrites',
        ),
        migrations.RemoveField(
            model_name='urine_test',
            name='ph_level',
        ),
        migrations.RemoveField(
            model_name='urine_test',
            name='protein',
        ),
        migrations.RemoveField(
            model_name='urine_test',
            name='specific_gravity_test',
        ),
        migrations.RemoveField(
            model_name='urine_test',
            name='urobilinogen',
        ),
        migrations.AddField(
            model_name='fasting_blood_sugar',
            name='docs_comments',
            field=models.CharField(max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='fasting_blood_sugar',
            name='next_fbs_test',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='full_blood_count',
            name='docs_comments',
            field=models.CharField(max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='full_blood_count',
            name='fbc_image_scan',
            field=models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='pic_folder/'),
        ),
        migrations.AddField(
            model_name='full_blood_count',
            name='lymphocyte',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='full_blood_count',
            name='neutrophil',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='urine_test',
            name='conclusion',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='urine_test',
            name='next_urine_test',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='urine_test',
            name='observation',
            field=models.CharField(max_length=5000, null=True),
        ),
    ]
