# Generated by Django 2.1.1 on 2018-12-21 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_lipid_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Renal_function_test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creatinine', models.CharField(max_length=255, null=True)),
                ('urea', models.CharField(max_length=255, null=True)),
                ('gfr', models.CharField(max_length=255, null=True)),
                ('test_date', models.DateField()),
                ('next_renal_test', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.AuthUserDemographic')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
