# Generated by Django 2.1.1 on 2018-12-21 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_renal_function_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='renal_function_test',
            old_name='test_date',
            new_name='renal_test_date',
        ),
    ]
