# Generated by Django 2.1.1 on 2018-12-21 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20181221_0131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lipid_profile',
            old_name='date',
            new_name='lipid_profile_date',
        ),
        migrations.AddField(
            model_name='renal_function_test',
            name='renal_scan',
            field=models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='pic_folder/'),
        ),
    ]
