# Generated by Django 2.1.1 on 2018-12-22 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20181222_2156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liver_function_test',
            name='albumin',
        ),
    ]
