# Generated by Django 2.1.1 on 2018-12-24 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_liver_function_test_albumin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='full_blood_count',
            old_name='test_scan',
            new_name='fbc_image_scan',
        ),
        migrations.RenameField(
            model_name='full_blood_count',
            old_name='date',
            new_name='full_blood_count_date',
        ),
        migrations.RenameField(
            model_name='full_blood_count',
            old_name='next_test_date',
            new_name='next_full_blood_count_date',
        ),
    ]
