# Generated by Django 2.1.1 on 2018-12-26 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_prostate_specific_antigen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prostate_specific_antigen',
            old_name='next_psa_text',
            new_name='next_psa_test',
        ),
    ]
