# Generated by Django 2.1.1 on 2019-01-10 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20181226_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='prostate_specific_antigen',
            name='docs_comments',
            field=models.CharField(max_length=3000, null=True),
        ),
    ]
