# Generated by Django 2.1.1 on 2019-01-10 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_prostate_specific_antigen_docs_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='prostate_specific_antigen',
            name='psa_scan',
            field=models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='pic_folder/'),
        ),
    ]
