# Generated by Django 2.1.1 on 2019-01-11 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20190111_2032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='urine_test',
            old_name='date',
            new_name='urine_test_date',
        ),
        migrations.RemoveField(
            model_name='urine_test',
            name='bilirubin',
        ),
        migrations.RemoveField(
            model_name='urine_test',
            name='blood_urine',
        ),
        migrations.RemoveField(
            model_name='urine_test',
            name='glucose',
        ),
        migrations.RemoveField(
            model_name='urine_test',
            name='leukocytes',
        ),
        migrations.RemoveField(
            model_name='urine_test',
            name='nitrites',
        ),
        migrations.RemoveField(
            model_name='urine_test',
            name='ph_level',
        ),
        migrations.RemoveField(
            model_name='urine_test',
            name='protein',
        ),
        migrations.RemoveField(
            model_name='urine_test',
            name='urobilinogen',
        ),
        migrations.AddField(
            model_name='urine_test',
            name='conclusion',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='urine_test',
            name='next_urine_test',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='urine_test',
            name='observation',
            field=models.CharField(max_length=5000, null=True),
        ),
    ]
