# Generated by Django 2.1.1 on 2019-01-24 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20190112_0024'),
    ]

    operations = [
        migrations.AddField(
            model_name='authuserdemographic',
            name='hospital_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='authuserdemographic',
            name='mdc_certificate',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='authuserdemographic',
            name='role',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='authuserdemographic',
            name='speciality',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
