# Generated by Django 2.1.1 on 2019-02-02 11:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0027_auto_20190127_0939'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('picture', models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='pic_folder/')),
                ('title', models.CharField(max_length=30, null=True)),
                ('first_name', models.CharField(max_length=255, null=True)),
                ('other_name', models.CharField(max_length=255, null=True)),
                ('unique_id', models.CharField(max_length=255, null=True)),
                ('surname', models.CharField(max_length=255, null=True, verbose_name='Surname')),
                ('sex', models.CharField(choices=[('Male', 'MALE'), ('Female', 'FEMALE')], default='Male', max_length=255, verbose_name='Gender')),
                ('date_of_birth', models.DateField(verbose_name='Date of Birth')),
                ('nationality', models.CharField(max_length=255, null=True)),
                ('religion', models.CharField(max_length=255, null=True)),
                ('address', models.CharField(max_length=255, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('mobile', models.CharField(max_length=255, null=True)),
                ('first_login', models.BooleanField(default=True)),
                ('speciality', models.CharField(max_length=255, null=True)),
                ('facility_name', models.CharField(max_length=255, null=True)),
                ('certificate', models.CharField(max_length=255, null=True)),
                ('role', models.CharField(max_length=225, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
