# Generated by Django 2.1.1 on 2019-02-07 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_patientpartnertransfer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientpartnertransfer',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to='core.AuthUserDemographic'),
        ),
        migrations.AlterField(
            model_name='patientpartnertransfer',
            name='partner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partner', to='core.Partners'),
        ),
        migrations.AlterField(
            model_name='patientpartnertransfer',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='core.AuthUserDemographic'),
        ),
    ]
