# Generated by Django 2.1.1 on 2019-02-07 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20190207_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='partners',
            name='marital_status',
            field=models.CharField(choices=[('Married', 'MARRIED'), ('Single', 'SINGLE')], default='Single', max_length=255),
        ),
        migrations.AlterField(
            model_name='patientpartnertransfer',
            name='status',
            field=models.CharField(default='Active', max_length=30, null=True),
        ),
    ]
