# Generated by Django 2.1.1 on 2019-02-08 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_auto_20190207_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partners',
            name='facility_name',
        ),
        migrations.AddField(
            model_name='partners',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Organization'),
        ),
    ]
