# Generated by Django 2.1.1 on 2019-02-25 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_drugs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='medicine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Drugs'),
        ),
    ]
