# Generated by Django 2.1.1 on 2019-02-25 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_auto_20190225_0808'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='strength',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
