# Generated by Django 2.1.1 on 2019-03-08 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_auto_20190308_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='reps_contact',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
