# Generated by Django 2.1.1 on 2019-03-08 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_auto_20190308_1846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='reps_contact',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='reps_email',
        ),
    ]
