# Generated by Django 2.1.1 on 2019-03-08 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_auto_20190308_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='reps_contact',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='reps_email',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
