# Generated by Django 2.1.1 on 2019-07-29 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_auto_20190308_1857'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logging',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(max_length=200, null=True)),
                ('reference_db', models.CharField(max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='authuserdemographic',
            name='marital_status',
            field=models.CharField(choices=[('Married', 'MARRIED'), ('Single', 'SINGLE'), ('Divorced', 'DIVORCED'), ('Widowed', 'WIDOWED')], default='Single', max_length=255),
        ),
        migrations.AddField(
            model_name='logging',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actor', to='core.AuthUserDemographic'),
        ),
        migrations.AddField(
            model_name='logging',
            name='affected_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.AuthUserDemographic'),
        ),
    ]
