# Generated by Django 2.1.1 on 2019-07-26 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_auto_20190308_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuserdemographic',
            name='marital_status',
            field=models.CharField(choices=[('Married', 'MARRIED'), ('Single', 'SINGLE'), ('Divorced', 'DIVORCED'), ('Widowed', 'WIDOWED')], default='Single', max_length=255),
        ),
    ]
