# Generated by Django 2.1.1 on 2019-07-31 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_auto_20190729_2235'),
        ('core', '0042_conditions'),
    ]

    operations = [
    ]
