# Generated by Django 2.1.1 on 2019-07-31 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_merge_20190731_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='authuserdemographic',
            name='emergency_contact_address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='authuserdemographic',
            name='emergency_contact_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='authuserdemographic',
            name='religion',
            field=models.CharField(choices=[('Christianity', 'Christianity'), ('Islam', 'Islam'), ('Traditional', 'Traditional'), ('Other', 'Other'), ('None', 'None')], max_length=255, null=True),
        ),
    ]
