# Generated by Django 2.1.1 on 2019-08-01 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_auto_20190731_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='authuserdemographic',
            name='city_and_town',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='authuserdemographic',
            name='denomination',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='authuserdemographic',
            name='region_of_residence',
            field=models.CharField(choices=[('Ahafo Region', 'Ahafo Region'), ('Ashanti Region', 'Ashanti Region'), ('Bono East Region', 'Bono East Region'), ('Bono Region', 'Bono Region'), ('Central Region', 'Central Region'), ('Eastern Region', 'Eastern Region'), ('Greater Accra Region', 'Greater Accra Region'), ('Northern Region', 'Northern Region'), ('North East Region', 'North East Region'), ('Oti Region', 'Oti Region'), ('Savannah Region', 'Savannah Region'), ('Upper East Region', 'Upper East Region'), ('Upper West Region', 'Upper West Region'), ('Volta Region', 'Volta Region'), ('Western Region', 'Western Region'), ('Western North Region', 'Western North Region')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='partners',
            name='city_and_town',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='partners',
            name='region_of_residence',
            field=models.CharField(choices=[('Ahafo Region', 'Ahafo Region'), ('Ashanti Region', 'Ashanti Region'), ('Bono East Region', 'Bono East Region'), ('Bono Region', 'Bono Region'), ('Central Region', 'Central Region'), ('Eastern Region', 'Eastern Region'), ('Greater Accra Region', 'Greater Accra Region'), ('Northern Region', 'Northern Region'), ('North East Region', 'North East Region'), ('Oti Region', 'Oti Region'), ('Savannah Region', 'Savannah Region'), ('Upper East Region', 'Upper East Region'), ('Upper West Region', 'Upper West Region'), ('Volta Region', 'Volta Region'), ('Western Region', 'Western Region'), ('Western North Region', 'Western North Region')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='authuserdemographic',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='partners',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='partners',
            name='religion',
            field=models.CharField(choices=[('Christianity', 'Christianity'), ('Islam', 'Islam'), ('Traditional', 'Traditional'), ('Other', 'Other'), ('None', 'None')], max_length=255, null=True),
        ),
    ]
