# Generated by Django 2.1.1 on 2019-08-09 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_speciality'),
    ]

    operations = [
        migrations.AddField(
            model_name='logging',
            name='transaction_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
